### ISSUE TITLE
Branches and CI platforms

### ISSUE THREAD

**Issue by sloretz** [ros/urdfdom#101]
Looking at #99 it appears the travis CI job failed due to it testing `master` on ubuntu trusty.

What's the purpose of each branch? What platform is each branch supposed to support? It looks like all branches besides `0.2`, `0.3`, `0.4`, and `master` are unused and could be removed.

Releases:
* Ubuntu trusty has [urdfdom 0.2.10](https://packages.ubuntu.com/trusty/liburdfdom-dev)
* Fedora 23 has [urdfdom 0.3.0](https://fedora.pkgs.org/23/fedora-i386/urdfdom-devel-0.3.0-10.fc23.i686.rpm.html)
* Fedora 24 has [urdfdom 0.3.0](https://fedora.pkgs.org/24/fedora-i386/urdfdom-devel-0.3.0-13.fc24.i686.rpm.html)
* Debian jessie has [urdfdom 0.3.0](https://packages.debian.org/jessie/liburdfdom-dev)
* Ubuntu xenial has [urdfdom 0.4.1](https://packages.ubuntu.com/xenial/liburdfdom-dev)
* Fedora 25 has [urdfdom 0.4.2](https://fedora.pkgs.org/25/fedora-i386/urdfdom-devel-0.4.2-1.fc25.i686.rpm.html)
* Fedora 26 has [urdfdom 0.4.2](https://fedora.pkgs.org/26/fedora-i386/urdfdom-devel-0.4.2-2.fc26.i686.rpm.html)
* Debian stretch has [urdfdom 1.0.0](https://packages.debian.org/stretch/liburdfdom-dev)
* Ubuntu yakkety has [urdfdom 1.0.0](https://packages.ubuntu.com/yakkety/liburdfdom-dev)
* Debian buster has [urdfdom 1.0.0](https://packages.debian.org/buster/liburdfdom-dev)
* Ubuntu zesty has [urdfdom 1.0.0](https://packages.ubuntu.com/zesty/liburdfdom-dev)
* Debian sid has [urdfdom 1.0.0.](https://packages.debian.org/sid/liburdfdom-dev)
* Ubuntu artful has [urdfdom 1.0.0](https://packages.ubuntu.com/artful/liburdfdom-dev)

Thoughts on having CI test the following platforms on each branch?
* `0.2`
  * Ubuntu trusty
* `0.3`
  * Fedora 23
  * Fedora 24
  * Debian jessie
* `0.4`
  * Ubuntu xenial
  * Fedora 25
  * Fedora 26
* `master`
  * Debian stretch
  * Ubuntu Yakkety
  * Debian buster
  * Ubuntu zesty
  * Debian sid
  * Ubuntu artful

**Comment by clalancette** [comment]
Since we collapsed all of the branches down to just "master" now, I'm going to close this out.  Feel free to reopen if I've misunderstood.
