### ISSUE TITLE
How to set torsional friction in URDF?

### ISSUE THREAD

**Issue by mcamurri** [ros/urdfdom#103]
I'm not sure whether this is the right place, but the official Bug Tracker [here](https://github.com/ros/robot_model) seems deprecated.

I'm raising this issue because when switching from Indigo/Gazebo 2 to Kinetic/Gazebo 7, the same model of a quadruped robot, which has feet with a perfectly spherical collision volume , doesn't work anymore, because it slips continuously.

I suspect that this is due the new torsional friction property from Gazebo 7.

With reference to the following Gazebo and ROS questions:
https://answers.ros.org/question/271474/robot-slips-after-upgrade-to-kinetic/?comment=271627#post-id-271627
http://answers.gazebosim.org/question/13082/how-do-i-add-torsional-friction-to-urdf-model/
http://answers.gazebosim.org/question/17457/robot-slips-after-upgrade-to-kinetic/

I can't find a way to set the torsional friction properties from the URDF file (which is then converted into a SDF when Gazebo launches).

Apparently, the `<gazebo>` tag does not do what I thought, i.e. injecting SDF code into the URDF.

If I put the SDF code to set the torsional friction from within the URDF, they are ignored.

**Comment by sloretz** [comment]
Hi @mcamurri, I think the the right place is [the sdformat repo](https://bitbucket.org/osrf/sdformat/src/53b56cfe7d8339e2fe65b2b0969567d0f7a7bb9c/src/parser_urdf.cc?at=sdf4&fileviewer=file-view-default#parser_urdf.cc-1612). Gazebo answers is even better. I added a new answer to http://answers.gazebosim.org/question/13082/how-do-i-add-torsional-friction-to-urdf-model/.

In short, the `<gazebo>` does sort-of inject SDF into URDF. Make a `<gazebo>` tag which references the `<link>` and has a `<collision name="...">` with the same name as the generated SDF `<collision>`.

I am closing this issue for now. Feel free to reopen if there is more you would like to discuss.
