### ISSUE TITLE
compiler warnings with Visual Studio 2017 due to gtest

### ISSUE THREAD

**Issue by dirk-thomas** [ros/urdfdom#107]
E.g.:

```
urdf_parser\test\gtest\include\gtest/gtest-printers.h(500):
warning C4996: 'std::tr1': warning STL4002:
The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning.
```

The warnings have been fixed upstream so pulling a newer version of the `googletest` code will likely solve this.

**Comment by dirk-thomas** [comment]
The warnings have been fixed upstream so pulling a newer version of the `googletest` code would solve this.

**Comment by dirk-thomas** [comment]
@scpeters Friendly ping.

**Comment by dirk-thomas** [comment]
@scpeters Can you comment on this issue if it is realistic that this will be addressed?

**Comment by scpeters** [comment]
see #110
