### ISSUE TITLE
functions to write urdf xml to file?

### ISSUE THREAD

**Issue by benaxelrod** [ros/urdfdom#12]
I am looking for functions to write a urdf xml file but can't seem to find any.  Basically, I am reading joint and body data from another file format, and would like to convert it to URDF.  

It looks like this functionality might exist in "urdf_parser_py", but i'm not sure.  Other than that, the only other thing i can find that looks like it writes urdf files is "robot_model/collada_urdf/src/collada_to_urdf.cpp".

Thanks

**Comment by jacquelinekay** [comment]
Using urdf_parser_py, the following sample code should work.

```
from urdf_parser_py.urdf import URDF

robot = URDF.from_xml_file("calvin.urdf")

# change robot model programatically

xml_string = robot.to_xml_string()
print xml_string
```

We could add this functionality to the C++ API and/or update the documentation for urdf_parser_py.

**Comment by benaxelrod** [comment]
Thanks, I would like the C++ API.

**Comment by sbarthelemy** [comment]
It already exists:

[TiXmlDocument* exportURDF(const ModelInterface &model);](https://github.com/ros/urdfdom/blob/8b27e0b6fbddbb4cc670156961bd52b4d5ea632b/urdf_parser/include/urdf_parser/urdf_parser.h#L64)

You can write to a file with something like this:
```
boost::scoped_ptr<TiXmlDocument> tiXmlDoc(urdf::exportURDF(mymodel));
TiXmlPrinter printer;
tiXmlDoc->Accept(&printer);
std::cout << printer.Str();
```

**Comment by sloretz** [comment]
Hi @benaxelrod, it looks like it has been a while since this was updated. I'm assuming the post by @sbarthelemy answers the question. Feel free to reopen if that's not the case.
