### ISSUE TITLE
Feature request: check_urdf should be able to read from std_in

### ISSUE THREAD

**Issue by nickswalker** [ros/urdfdom#170]
Like `urdfdom_py`'s `display_urdf` script, check_urdf should accept `-` as an argument to indicate that it should read the URDF from std_in. This makes piping input directly from xacro more natural. This is a simple modification that I can contribute at some point.

**Comment by rhaschke** [comment]
Such a contribution would be very welcome.

**Comment by nickswalker** [comment]
Bumping this issue. It looks like the PR is approved so hopefully a maintainer has some time to merge it
