### ISSUE TITLE
Use tinyxml2 instead of tinyxml

### ISSUE THREAD

**Issue by felixf4xu** [ros/urdfdom#185]
Hi,

I'm trying to compile ros2 from source on Windows 11 and `urdfdom` is the only repo that I need to change the code manually.

The reason is the dependency of "tinyxml" and I really hope "tinyxml2" should be used.

Reason:
- Tinyxml is not maintained for 10 years
- Tinyxml uses `catkin` which is not usually used in ROS2
- Tinyxml2 is another popular project and its main purpose is to replace the outdated tinyxml

When I check the code and issues, I found that the current branch of [scpeters/tinyxml2] (https://github.com/ros/urdfdom/tree/scpeters/tinyxml2) did exactly what I wanted and it also provides a cmake option to be back compatible (which  I don't think is necessary, though)

So, please merge the branch and say goodbye to tinyxml.

**Comment by chging** [comment]
i have the same question, why not use tinyxml2

**Comment by scpeters** [comment]
this will be fixed by https://github.com/ros/urdfdom/pull/186
