### ISSUE TITLE
CMake 3.30: urdfdom_parser fails to build

### ISSUE THREAD

**Issue by oysstu** [ros/urdfdom#203]
Urdfdom_parser fails to build due to the following lines
https://github.com/ros/urdfdom/blob/29426ec119e9c3a9df9fc705d08c262a97b7f285/urdf_parser/CMakeLists.txt#L77-L80

The following error is output
```
CMake Error at urdf_parser/CMakeLists.txt:77 (target_link_libraries):
  The link interface of target "urdf_parser" contains:

    urdfdom::urdfdom_model

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

Removing urdfdom:: from all three targets resolves the issue. Not sure if this causes older cmake versions to fail.

**Comment by scpeters** [comment]
Thanks, I've reproduced the error on macOS and opened #204 with your suggested fix after confirming it locally.
