### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by davetcoleman** [ros/urdfdom#30]
Can we release the latest updates in this repo to Ubuntu?

**Comment by VahidAminZ** [comment]
Are there going to be a release soon? The parser does not work with the new URDF format.

**Comment by jacquelinekay** [comment]
@wjwwood, @isucan, and I are working on a release this week.

**Comment by wjwwood** [comment]
We don't actually have control over the version of this in Ubuntu. We'll look into who needs to do what to get a newer version in the latest Ubuntu, but it's very likely we cannot put a newer version into Trusty since these are not critical bug fixes.

**Comment by scpeters** [comment]
Please consider releasing `urdfdom_headers` as well

**Comment by VahidAminZ** [comment]
@wjwwood: but the current version in Trusty fails to parse urdfs with latest format. I think that is considered a critical bug.

**Comment by wjwwood** [comment]
@VahidAminZ I would tend to agree with you, but I think the Debian and Ubuntu maintainers would not. Either way I'll let @hsu or @j-rivero comment on that.

**Comment by jacquelinekay** [comment]
Here are the options I see:

1. Do nothing and wait until our next opportunity to get the updates to urdfdom/urdfdom_headers into Ubuntu. This is my least favorite option since it's further delaying a release that users have needed for 1.5 years, but it requires the least amount of work for the package maintainers.

2. Try to convince the Ubuntu maintainers to emergency release urdfdom/urdfdom_headers into Trusty because of critical bug fixes. This is a clean and relatively low-effort solution; however, William already pointed out that the Ubuntu maintainers might not consider the changes critical.

3. OSRF (probably @j-rivero...) rolls new `.deb`s for `liburdfdom-dev` and `liburdfdom-headers-dev` and bumps the version number, and makes that available for users on `packages.ros.org` until the next Ubuntu version. Messy, since the Ubuntu system package will hang around for most users.

I don't know quite enough about the repercussions of 3 to know if it's a terrible idea, but I think we should try 2 ASAP and have 3 available as a backup plan.

Thoughts?

**Comment by wjwwood** [comment]
Certainly option 2 is preferable, but we'll have to see if that's an option. It maybe at least an option for the next Ubuntu LTS and Kinetic.

For option 3, we just have to be careful that either our version of `urdfdom` is ABI compatible with the current one or all packages which use our custom version of `urdfdom` are also replicated and put on packages.ros.org. For example, if our `urdfdom` is not ABI compatible with the one in Ubuntu and we combine our `urdfdom` with say `sdformat` (which uses the Ubuntu version of `urdfdom`) then we'll have a problem.

**Comment by mikeferguson** [comment]
What about putting something into trusty-updates? I'm not entirely sure how that works as far as difficulty of releasing, but I'm pretty sure the ROS buildfarm already requires trusty-updates because we are using the version of Boost that is there (I don't know if the OSRF Gazebo farm is using trusty-updates).

**Comment by j-rivero** [comment]
From my perspective as the debian/ubuntu maintainer:

* **Ubuntu Trusty**: the changes of getting something more than a small patch into the current Trusty release are really low. I'm [still waiting for an answer on my last request](https://bugs.launchpad.net/ubuntu/+source/urdfdom-headers/+bug/1471047). [Stable release updates policy](https://wiki.ubuntu.com/StableReleaseUpdates) is strict, although [lately Ubuntu changed the rules](https://lists.ubuntu.com/archives/ubuntu-devel-announce/2015-September/001152.html) to make it more easy for updates, what I think is good news for us.

* **Ubuntu Trusty updates:** `-proposed` and `-updates` are used as testing parts of SRUs (stable release updates). The change is released in `-proposed` and wait for validation before being moved to `-updates`. You can see how [this works on our SRU for sdformat](https://bugs.launchpad.net/ubuntu/+source/sdformat/+bug/1338845). AFAIK, there is no way of going into `-updates` without an SRU once the distribution is released.

* **Ubuntu Trusty backports:** [backports](https://help.ubuntu.com/community/UbuntuBackports) sounds like the best fit for our use case. New features and improvements (not necessarily bug fixes) which enhances a released distro.

Any change we want to send to Trusty must keep ABI/API stability.

* **Ubuntu Wily and Ubuntu-X:** * the release cycle of Ubuntu Wily is closed and the release will happen sometime soon. No chances of getting changes into it. Ubuntu-X release cycle will open soon and yes, we have some months to get changes shipped, even the ones that break ABI/API.

* **Import urdfdom packages to ROS repo:** the quickest option but with some risks. As William pointed before, we also need to be sure about ABI/API so we don't break ROS and other software which depends on urdfdom.

**Comment by jacquelinekay** [comment]
Here's my understanding of the situation:

The currently released version of liburdfdom/liburdfdom-headers in Trusty is 0.2.10.

The last release was 0.3.0, into Utopic. `master` branch is not API/ABI compatible with 0.2.10.

Several of the critical issues that @davetcoleman, @adolfo-rt, @goretkin, @k-okada, etc. have pointed out with this library were merged into `master` after the 0.2.10 release.

I propose we make an API/ABI-compatible 0.2.11 release for Trusty with backported fixes of several critical PRs and try to get it into backports. I will make a branch that we can target backport pull requests to. We can do the same for urdfdom_headers

Can I get some help from the people tagged in this post and other upstanding citizens who want a new release of urdfdom into Trusty to list PRs and commits that need to get backported? Even better would be to provide PRs into the 0.2.11 branch.

Issues to resolve with backport/release of 0.2.11:
#36 

Candidate backport PRs:
#63

**Comment by jacquelinekay** [comment]
Also, it seems like there are a lot of problems specific to ros-indigo-urdfdom-py, which is currently on 0.3.0 in Trusty.

According to the package.xml that apt installs on my computer, it does not have a dependency on liburdfdom or liburdfdom-headers. But, I couldn't find a branch or tag in this repository that shows what gets released with `urdfdom_py`.

Maybe @isucan can weigh in here. If we can release 0.3.1 of `urdfdom_py` into Trusty without going through Ubuntu, that would be really helpful.

**Comment by jacquelinekay** [comment]
Double-posted from a pull request comment--here's the plan we devised today.

I just made two new branches, 0.2.12 and 0.3.1.

0.2.12 targets Trusty.

0.3.1 targets Ubuntu Utopic and Vivid.

We will target backwards-compatible bugfixes into these branches.

@scpeters and I are trying to release urdfdom 0.4 today, which will allow API/ABI changes. We are trying to get this version released into Ubuntu X (Xenial Xerus).

**Comment by k-okada** [comment]
does this mean for example jade running on trusty and utopic need to use
different version of urdfdom, is it correct?
Is there any reason why you did not targeting 0.2.12 to indigo and 0.3.x to
jade?

--
◉ Kei Okada

**Comment by scpeters** [comment]
urdfdom is now a system library, so ROS indigo and jade should be able to use whichever version is provided by the system.

**Comment by k-okada** [comment]
I see, so you do not use urdfdom-release any more, thanks !

2015年12月10日木曜日、Steven Peters<notifications@github.com>さんは書きました:

> urdfdom is now a system library, so ROS indigo and jade should be able to
> use whichever version is provided by the system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ros/urdfdom/issues/30#issuecomment-163434802>.
>


-- 
--
◉ Kei Okada

**Comment by sloretz** [comment]
I'm not sure if this is solved, but I'll close it for now.

I can't tell which version needed to be released into which ubuntu version from the title and original post; however, reading through the thread I see references to releasing 0.4 to xenial. Ubuntu Yakkety and above have version 1.0.0 so it seems likely that whatever needed to be released was released.
