### ISSUE TITLE
pykdl_utils

### ISSUE THREAD

**Issue by kphawkins** [ros/urdfdom#40]
As I mentioned in emails long ago, I have developed a Python utility package for kinematics: https://github.com/gt-ros-pkg/hrl-kdl/tree/hydro/pykdl_utils/src/pykdl_utils.  It allows you to use the URDF Python parser to generate a PyKDL tree (`kdl_parser.py`).  Furthermore, I have written a helper class called `KDLKinematics` which conveniently wraps PyKDL with numpy wrappers.  Finally, `JointKinematics` extends `KDLKinematics` to automatically read in joint states from the topic `/joint_states`, so that forward kinematics can be called without parameters.

Here's an example from `kdl_kinematics.py`:

```
from urdf_parser_py.urdf import Robot
import random
robot = Robot.from_parameter_server()
base_link = robot.get_root()
end_link = robot.link_map.keys()[random.randint(0, len(robot.link_map)-1)]
print "Root link: %s; Random end link: %s" % (base_link, end_link)
kdl_kin = KDLKinematics(robot, base_link, end_link)
q = kdl_kin.random_joint_angles()
print "Random angles:", q
pose = kdl_kin.forward(q)
print "FK:", pose
q_new = kdl_kin.inverse(pose)
print "IK (not necessarily the same):", q_new
if q_new is not None:
    pose_new = kdl_kin.forward(q_new)
    print "FK on IK:", pose_new
    print "Error:", np.linalg.norm(pose_new * pose**-1 - np.mat(np.eye(4)))
else:
    print "IK failure"
J = kdl_kin.jacobian(q)
print "Jacobian:", J
M = kdl_kin.inertia(q)
print "Inertia matrix:", M
if False:
    M_cart = kdl_kin.cart_inertia(q)
    print "Cartesian inertia matrix:", M_cart
```

I feel like this can be of great use to some people and I'd like to release it somewhere where people are more likely to find it.  @isucan is there a good place to integrate this and is there reasonable demand for something like this?

**Comment by goretkin** [comment]
+1, I think this is very important functionality that has been available for C++ nodes under http://wiki.ros.org/pr2_mechanism_model#Chain but has been easily available in Python (see post from 2010: http://lists.willowgarage.com/pipermail/pr2-users/2010-July/000970.html)

**Comment by jacquelinekay** [comment]
Funny enough, @jbohren contributed something similar to this in ros/robot_model#74, and I did a bit of reshuffling to put it in its own ROS package, `kdl_parser_py`.

I was just thinking though that it's a bit odd that `kdl_parser` and the upcoming `kdl_parser_py` aren't dependent of ROS, however, since in their most distilled form they would only depend on `urdfdom`. Right now they depend on it indirectly through their dependency on the `urdf` ROS package.

**Comment by sloretz** [comment]
Looks like it's been a while since this was updated. @kphawkins I think the [kdl_parser repo](https://github.com/ros/kdl_parser) would be a great place to integrate `pykdl_utils`.

I'll close this issue, but feel free to reopen.
