### ISSUE TITLE
urdfdom found but not a catkin package

### ISSUE THREAD

**Issue by rojas70** [ros/urdfdom#43]
I am working with Ubuntu 12.04 and ROS Hydro. I am also following the Baxter PyKDL Tutorial at http://sdk.rethinkrobotics.com/wiki/Baxter_PyKDL.

Upon running catkin_make, I get the following error:
````
-- ==> add_subdirectory(baxter_pykdl)
CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a configuration file for package python_orocos_kdl.

  Set python_orocos_kdl_DIR to the directory containing a CMake configuration
  file for python_orocos_kdl.  The file will have one of the following names:

    python_orocos_kdlConfig.cmake
    python_orocos_kdl-config.cmake

Call Stack (most recent call first):
  baxter_pykdl/CMakeLists.txt:4 (find_package)


-- Using these message generators: gencpp;genlisp;genpy
CMake Error at /opt/ros/hydro/share/catkin/cmake/catkin_package.cmake:176 (message):
  catkin_package() CATKIN_DEPENDS on 'urdfdom', which has been found in
  '/opt/ros/hydro/share/urdfdom/cmake/urdfdom-config.cmake', but it is not a
  catkin package
Call Stack (most recent call first):
  /opt/ros/hydro/share/catkin/cmake/catkin_package.cmake:98 (_catkin_package)
  baxter_pykdl/CMakeLists.txt:19 (catkin_package)


-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
````

It seems the culprit is urdfdom. 

I have removed and reinstalled urdfdom and related binaries for hydro. I have also re-tried to catkin_make from scratch.

I am able to roscd to urdfdom. It takes me to `/opt/ros/hydro/share/urdfdom`. Inside, however I only see a `cmake` folder and the `package.xml` file. 

I tried to run `rosrun urdfdom check_urdf baxter.urdf` but I don't have such executable. I also got an error trying to use urdfdom_py display_urdf.

Any thoughts?

**Comment by jacquelinekay** [comment]
Closing this for now (esp. since Hydro is EOL'd).
