### ISSUE TITLE
the C++ quaternion/rpy conversion has numerical issues

### ISSUE THREAD

**Issue by sbarthelemy** [ros/urdfdom#49]
two very similar quaternions can result in different and non-equivalent roll pitch yaw angles.

Unint test showing the issue coming soon.

**Comment by vrabaud** [comment]
@hsu  , it seems that code comes from Gazebo that has the same problem:
https://bitbucket.org/osrf/gazebo/src/66de1887edea28bec5d8b94de5e74f035ac53cc0/gazebo/math/Quaternion.cc?at=default#cl-257

**Comment by scpeters** [comment]
Gazebo developer here; @j-rivero and I will look into adding that unit test to the gazebo math library.

We've thought about eigen but don't have any short-term plans to incorporate it into the default gazebo math library. Gazebo can optionally link with the [dartsim physics engine](https://github.com/dartsim/dart), but that's currently the only connection with eigen that I know of.

**Comment by j-rivero** [comment]
By the way, gazebo6 has split out the math layer and create a common library for it, called [ignition robotics math](http://ignitionrobotics.org/libraries/math). Eventually, I agree with @traversaro, it would be nice to use Eigen as a backend.

**Comment by scpeters** [comment]
fixed by https://github.com/ros/urdfdom_headers/pull/11
