### ISSUE TITLE
file provided by catkin not found in ubuntu

### ISSUE THREAD

**Issue by parijohn** [ros/urdfdom#69]
hi everyone, I am tring to run make command for serialmaster program in ubuntu 14, but it gives following error Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.
 help anyone?

**Comment by jacquelinekay** [comment]
This kind of question is more appropriate for answers.ros.org than the Github issue tracker. In the future, can you make sure the issue is caused by an issue in the codebase before posting it on the Github issue tracker?
