### ISSUE TITLE
 Create the release 1.0.0

### ISSUE THREAD

**Issue by j-rivero** [ros/urdfdom#92]
I believe that after the merge of pull request #62  we are ready to tag and release the version 1.0.0.  
If there is anything missing, please let me know.  

//cc @scpeters

**Comment by scpeters** [comment]
There are some outstanding pull requests, but they are proposing new features, which we still need to figure out how to handle. I think we can go with 1.0

**Comment by j-rivero** [comment]
Agree. I don't have perms to create the release, could you please generate it?

**Comment by scpeters** [comment]
draft:

* https://github.com/ros/urdfdom/releases/tag/untagged-9211ae09e91a28ad74ce

**Comment by scpeters** [comment]
I also created a `0.4` branch which is two pull requests ahead of 0.4.2

* #88 
* #89

**Comment by scpeters** [comment]
https://github.com/ros/urdfdom/releases/tag/untagged-1789fe5a1ae3ecd8f919

**Comment by j-rivero** [comment]
> https://github.com/ros/urdfdom/releases/tag/untagged-1789fe5a1ae3ecd8f919

Probably reserve for repo admins only, 404 for me.

**Comment by scpeters** [comment]
https://github.com/ros/urdfdom/releases/tag/1.0.0
